export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_BY_ID_REQUEST = "GET_PRODUCTS_BY_ID_REQUEST";
export const GET_PRODUCTS_BY_ID_SUCCESS = "GET_PRODUCTS_BY_ID_SUCCESS";
export const GET_PRODUCTS_BY_ID_FAIL = "GET_PRODUCTS_BY_ID_FAIL";
